"""Hook tools — generate and run Frida/LSPosed hook scripts with version tracking."""
import json
import os
import re
import subprocess
from pathlib import Path


# ── Hook script templates ──────────────────────────────────────────

FRIDA_HOOK_TEMPLATE = """// Auto-generated by reverse-skills hook_gen_frida
// Version: {version} | Preset: {preset} | Target: {package}
//
// Hook strategy: {strategy}
// {safety_notes}

Java.perform(function() {{
{hooks}
}});
"""

CLASS_HOOK_TEMPLATE = """    var {class_name} = Java.use("{full_class}");
    {class_name}.{method}.implementation = function({params}) {{
        var result = this.{method}({params});
        console.log("[REVERSE] {full_class}.{method}(" + {log_params} + ") = " + result);
        send({{"class": "{full_class}", "method": "{method}", "args": [{send_params}], "result": result.toString()}});
        return result;
    }};
"""

# App-layer hook: capture createCall params by calling interface methods inside the hook
CREATE_CALL_HOOK = """    var {class_name} = Java.use("{full_class}");
    {class_name}.{method}.implementation = function({params}) {{
        // Call interface methods on the request object BEFORE proceeding
        var path = "";
        var httpMethod = "";
        try {{ path = {param_name}.getPath(); }} catch(e) {{}}
        try {{ httpMethod = {param_name}.getHttpMethod(); }} catch(e) {{}}
        console.log("[REVERSE] createCall: " + httpMethod + " " + path);
        send({{"hook": "createCall", "method": httpMethod, "path": path}});
        var result = this.{method}({params});
        return result;
    }};
"""

# ── Default target presets ─────────────────────────────────────────

CRYPTO_TARGETS = [
    ("javax.crypto.Cipher", "getInstance", ["transformation"]),
    ("javax.crypto.Cipher", "doFinal", ["bytes"]),
    ("javax.crypto.Cipher", "init", ["mode", "key"]),
    ("java.security.MessageDigest", "getInstance", ["algorithm"]),
    ("java.security.MessageDigest", "digest", ["bytes"]),
    ("javax.crypto.spec.SecretKeySpec", "<init>", ["key", "algorithm"]),
    ("javax.crypto.Mac", "getInstance", ["algorithm"]),
    ("javax.crypto.Mac", "doFinal", ["bytes"]),
]

SSL_UNPIN_TARGETS = [
    ("javax.net.ssl.SSLContext", "init", ["keyManagerFactory", "trustManagerFactory", "secureRandom"]),
    ("javax.net.ssl.TrustManagerFactory", "init", ["keyStore"]),
]

APP_LAYER_TARGETS = [
    # OkHttp — request building and traffic indication
    ("okhttp3.RequestBuilder", "header", ["name", "value"]),
    ("okhttp3.OkHttpClient", "newCall", ["request"]),
    # Generic: Body.getData (Kotlin data class getter)
    ("okhttp3.RequestBody", "getData", []),
]

GSON_TARGETS = [
    ("com.google.gson.Gson", "toJson", ["obj"]),
]


# ── Preset safety notes ────────────────────────────────────────────

SAFETY_NOTES = {
    "crypto": "Safe: system crypto classes. OK for all packers including NIS.",
    "ssl": "Safe: system SSL classes. May crash on 360-packed apps.",
    "app_layer": "Safe if targeted. Do NOT enumerate classes or use reflection. NIS compatible if single-class hook.",
    "gson": "Unstable on NIS: watch call frequency. Use selectively on specific endpoints.",
    "full": "WARNING: Combined hook. May trigger NIS detection. Use only on non-packed or after confirming safety.",
}

STRATEGY_NOTES = {
    "crypto": "bottom-up (system layer)",
    "ssl": "bottom-up (system layer)",
    "app_layer": "top-down (app layer first)",
    "gson": "mid-layer (serialization)",
    "full": "multi-layer (app + crypto + serialization)",
}


# ── Tool implementations ───────────────────────────────────────────

def hook_gen_frida(target_classes: list[str] | None = None,
                   script_type: str = "crypto",
                   package: str = "",
                   output_dir: str | None = None) -> dict:
    """Generate a Frida JavaScript hook script with version tracking.

    Args:
        target_classes: List of "com.example.ClassName.method" strings.
                        If None, uses defaults based on script_type preset.
        script_type: Preset — "crypto", "ssl", "app_layer", "gson", or "full".
        package: Target app package name (for version tracking directory).
        output_dir: Directory to save script. Auto-creates subdir if package provided.
    """
    if target_classes:
        targets = []
        for tc in target_classes:
            parts = tc.rsplit('.', 1)
            if len(parts) == 2:
                targets.append((parts[0], parts[1], []))
            else:
                targets.append((tc, "*", []))
    elif script_type == "ssl":
        targets = SSL_UNPIN_TARGETS
    elif script_type == "app_layer":
        targets = APP_LAYER_TARGETS
    elif script_type == "gson":
        targets = GSON_TARGETS
    elif script_type == "full":
        targets = CRYPTO_TARGETS + APP_LAYER_TARGETS + GSON_TARGETS
    else:
        targets = CRYPTO_TARGETS

    # Build hook code
    hooks_code = []
    for full_class, method, params in targets:
        class_name = full_class.replace('.', '_')
        param_str = ', '.join(params) if params else ''
        log_str = ' + ", " + '.join(params) if params else '""'
        send_str = ', '.join(f'{p}.toString()' for p in params) if params else ''

        # Use createCall-specific template for app-layer methods that need param inspection
        if method == "newCall" and "OkHttpClient" in full_class:
            # Standard hook for newCall — just log the request
            hooks_code.append(CLASS_HOOK_TEMPLATE.format(
                class_name=class_name, full_class=full_class, method=method,
                params=param_str, log_params=log_str, send_params=send_str
            ))
        elif method == "getData" and "RequestBody" in full_class:
            # Body.getData — return bytes, log length
            hooks_code.append(f"""    var {class_name} = Java.use("{full_class}");
    {class_name}.{method}.implementation = function({param_str}) {{
        var result = this.{method}({param_str});
        console.log("[REVERSE] Body.getData() = " + result.length + " bytes");
        send({{"hook": "Body.getData", "bytes": result.length, "hex": bytesToHex(result)}});
        return result;
    }};

    function bytesToHex(bytes) {{
        var hex = [];
        for (var i = 0; i < Math.min(bytes.length, 128); i++) {{
            hex.push(("0" + (bytes[i] & 0xFF).toString(16)).slice(-2));
        }}
        return hex.join("");
    }}
""")
        else:
            hooks_code.append(CLASS_HOOK_TEMPLATE.format(
                class_name=class_name, full_class=full_class, method=method,
                params=param_str, log_params=log_str, send_params=send_str
            ))

    # Version tracking: auto-increment version in output dir
    version = 1
    if output_dir and package:
        hook_dir = Path(output_dir) / "hooks"
        hook_dir.mkdir(parents=True, exist_ok=True)
        existing = sorted(hook_dir.glob(f"{script_type}_v*.js"))
        if existing:
            last = existing[-1].stem
            m = re.search(r'v(\d+)$', last)
            if m:
                version = int(m.group(1)) + 1
        output_path = str(hook_dir / f"{script_type}_v{version}.js")
    elif output_dir:
        output_path = str(Path(output_dir) / f"hook_{script_type}.js")
    else:
        output_path = None

    script = FRIDA_HOOK_TEMPLATE.format(
        version=f"v{version}",
        preset=script_type,
        package=package or "unknown",
        strategy=STRATEGY_NOTES.get(script_type, "custom"),
        safety_notes=SAFETY_NOTES.get(script_type, ""),
        hooks='\n'.join(hooks_code)
    )

    if output_path:
        Path(output_path).write_text(script, encoding='utf-8')
        return {
            "status": "OK",
            "output_path": output_path,
            "version": version,
            "preset": script_type,
            "target_count": len(targets),
            "targets": [f"{c}.{m}" for c, m, _ in targets],
            "safety": SAFETY_NOTES.get(script_type, ""),
        }

    return {"status": "OK", "script": script, "version": version,
            "preset": script_type, "target_count": len(targets)}


def hook_run(method: str, script_path: str, package: str,
             server_path: str | None = None, timeout: int = 60) -> dict:
    """Run a hook script using Frida or hluda.

    Args:
        method: "frida" (spawn), "hluda" (attach via hluda-server),
                "frida-attach" (attach via frida-server), "gadget", "lsposed"
        script_path: Path to the hook script
        package: Target app package name
        server_path: Path to hluda-server binary (for method="hluda")
        timeout: Max seconds to run before timing out
    """
    if not Path(script_path).exists():
        return {"status": "ERROR", "error": f"Script not found: {script_path}"}

    if method in ("frida",):
        # Spawn mode — app is restarted with frida injected
        try:
            result = subprocess.run(
                ["frida", "-U", "-l", script_path, "-f", package, "--no-pause"],
                capture_output=True, text=True, timeout=timeout
            )
            crashed = "SIGSEGV" in (result.stderr + result.stdout)
            detected = crashed or "process terminated" in result.stdout.lower()
            return {
                "status": "DETECTED" if detected else "OK",
                "mode": "spawn",
                "stdout": result.stdout[:3000],
                "stderr": result.stderr[:500],
                "crashed": crashed,
                "detected": detected,
            }
        except subprocess.TimeoutExpired:
            return {"status": "TIMEOUT", "stdout": "", "stderr": "Frida timed out", "mode": "spawn"}
        except FileNotFoundError:
            return {"status": "ERROR", "error": "frida not installed. pip install frida-tools"}

    elif method in ("hluda", "frida-attach"):
        # Attach mode — app already running, inject into process
        # hluda-server must be running on device (started in Phase 0.5)
        try:
            result = subprocess.run(
                ["frida", "-U", "-l", script_path, "-n", package, "--no-pause"],
                capture_output=True, text=True, timeout=timeout
            )
            crashed = "SIGSEGV" in (result.stderr + result.stdout)
            detected = crashed or "process terminated" in result.stdout.lower()

            # Check if attach failed (app not running, etc.)
            if "unable to find process" in result.stderr.lower():
                return {
                    "status": "ERROR",
                    "error": f"Process '{package}' not found. Is the app running? Start it first.",
                    "mode": "attach",
                }

            return {
                "status": "DETECTED" if detected else "OK",
                "mode": "attach",
                "server": "hluda" if method == "hluda" else "frida-server",
                "stdout": result.stdout[:3000],
                "stderr": result.stderr[:500],
                "crashed": crashed,
                "detected": detected,
            }
        except subprocess.TimeoutExpired:
            return {"status": "OK", "mode": "attach",
                    "note": "Hook running (timeout reached). Script may still be active.",
                    "stdout": "", "stderr": ""}
        except FileNotFoundError:
            return {"status": "ERROR", "error": "frida not installed. pip install frida-tools"}

    elif method == "gadget":
        return {
            "status": "TODO",
            "note": "Frida Gadget requires injecting libfrida-gadget.so into the APK. "
                    "Use apk_unpack → inject libfrida-gadget.so → repackage → install.",
        }

    elif method == "lsposed":
        return {
            "status": "TODO",
            "note": "LSPosed requires building and installing an Xposed module APK.",
        }

    return {"status": "ERROR", "error": f"Unknown method: {method}. Use: frida, hluda, frida-attach, gadget, lsposed"}


def hook_gen_lsposed(hook_targets: dict | None = None, output_dir: str | None = None) -> dict:
    """Generate an LSPosed/Xposed module skeleton for persistent hooks."""
    return {
        "status": "OK",
        "note": "LSPosed module generation requires Android Studio build toolchain. "
                "Use hook_gen_frida for quick hooking; LSPosed is for persistent hooks.",
    }
