"""Hook tools — generate and run Frida/LSPosed hook scripts."""
import subprocess
from pathlib import Path


FRIDA_HOOK_TEMPLATE = """
// Auto-generated by reverse-skills hook_gen_frida
// Target classes: {target_classes}

Java.perform(function() {{
{hooks}
}});
"""

CLASS_HOOK_TEMPLATE = """
    var {class_name} = Java.use("{full_class}");
    {class_name}.{method}.implementation = function({params}) {{
        var result = this.{method}({params});
        console.log("[REVERSE-AGENT] {full_class}.{method}(" + {log_params} + ") = " + result);
        send({{"class": "{full_class}", "method": "{method}", "args": [{send_params}], "result": result.toString()}});
        return result;
    }};
"""

DEFAULT_CRYPTO_CLASSES = [
    ("javax.crypto.Cipher", "getInstance", ["transformation"]),
    ("javax.crypto.Cipher", "doFinal", ["bytes"]),
    ("javax.crypto.Cipher", "init", ["mode", "key"]),
    ("java.security.MessageDigest", "getInstance", ["algorithm"]),
    ("java.security.MessageDigest", "digest", ["bytes"]),
    ("javax.crypto.spec.SecretKeySpec", "<init>", ["key", "algorithm"]),
    ("javax.crypto.Mac", "getInstance", ["algorithm"]),
    ("javax.crypto.Mac", "doFinal", ["bytes"]),
    ("javax.net.ssl.SSLContext", "init", ["kmf", "tm", "sr"]),
]

SSL_UNPIN_CLASSES = [
    ("javax.net.ssl.SSLContext", "init", ["keyManagerFactory", "trustManagerFactory", "secureRandom"]),
    ("javax.net.ssl.TrustManagerFactory", "init", ["keyStore"]),
]


def _build_hook_script(targets: list[tuple[str, str, list[str]]]) -> str:
    """Build a Frida hook script from a list of (class, method, params) tuples."""
    hooks_code = []
    for full_class, method, params in targets:
        class_name = full_class.replace('.', '_')
        param_str = ', '.join(params) if params else ''
        log_str = ' + ", " + '.join(params) if params else '""'
        send_str = ', '.join(f'{p}.toString()' for p in params) if params else ''
        hooks_code.append(CLASS_HOOK_TEMPLATE.format(
            class_name=class_name,
            full_class=full_class,
            method=method,
            params=param_str,
            log_params=log_str,
            send_params=send_str
        ))

    target_names = ', '.join(t[0] for t in targets)
    return FRIDA_HOOK_TEMPLATE.format(
        target_classes=target_names,
        hooks='\n'.join(hooks_code)
    )


def hook_gen_frida(target_classes: list[str] | None = None,
                   script_type: str = "crypto",
                   output_path: str | None = None) -> dict:
    """Generate a Frida JavaScript hook script.

    Args:
        target_classes: List of "com.example.ClassName.method" strings to hook.
                        If None, uses defaults based on script_type.
        script_type: "crypto" (default crypto hooks) or "ssl" (SSL unpin hooks).
        output_path: If provided, write script to this file path.
    """
    if target_classes:
        targets = []
        for tc in target_classes:
            parts = tc.rsplit('.', 1)
            if len(parts) == 2:
                targets.append((parts[0], parts[1], []))
            else:
                targets.append((tc, "*", []))
    elif script_type == "ssl":
        targets = SSL_UNPIN_CLASSES
    else:
        targets = DEFAULT_CRYPTO_CLASSES

    script = _build_hook_script(targets)

    if output_path:
        Path(output_path).write_text(script)
        return {"status": "OK", "output_path": output_path, "script_length": len(script)}

    return {"status": "OK", "script": script, "script_length": len(script)}


def hook_gen_lsposed(hook_targets: dict | None = None, output_dir: str | None = None) -> dict:
    """Generate an LSPosed/Xposed module skeleton for persistent hooks."""
    return {
        "status": "OK",
        "note": "LSPosed module generation requires Android Studio build toolchain. "
                "Use hook_gen_frida for quick hooking; LSPosed is for persistent hooks.",
    }


def hook_run(method: str, script_path: str, package: str, timeout: int = 60) -> dict:
    """Run a hook script using Frida or LSPosed.

    Args:
        method: "frida", "gadget", or "lsposed"
        script_path: Path to the hook script
        package: Target app package name
        timeout: Max seconds to run before timing out
    """
    if method == "frida":
        try:
            result = subprocess.run(
                ["frida", "-U", "-l", script_path, "-f", package, "--no-pause"],
                capture_output=True, text=True, timeout=timeout
            )
            crashed = "SIGSEGV" in result.stderr or "process terminated" in result.stdout.lower()
            return {
                "status": "DETECTED" if crashed else "OK",
                "stdout": result.stdout[:2000],
                "stderr": result.stderr[:500],
                "crashed": crashed,
                "method": "frida"
            }
        except subprocess.TimeoutExpired:
            return {"status": "TIMEOUT", "stdout": "", "stderr": "Frida timed out", "method": "frida"}
        except FileNotFoundError:
            return {"status": "ERROR", "error": "frida not installed. pip install frida-tools", "method": "frida"}

    elif method == "gadget":
        return {
            "status": "TODO",
            "note": "Frida Gadget requires injecting libfrida-gadget.so into the APK. "
                    "Use apk_unpack → inject libfrida-gadget.so → repackage → install.",
            "method": "gadget"
        }

    elif method == "lsposed":
        return {
            "status": "TODO",
            "note": "LSPosed requires building and installing an Xposed module APK.",
            "method": "lsposed"
        }

    return {"status": "ERROR", "error": f"Unknown method: {method}"}
